---
abstract: 'Create Perl distributions with VCS and selectable toolchain'
author:
  - 'Peter Flanigan, C<< <pjfl@cpan.org> >>'
build_requires:
  Exception::Class: 1.23
  File::DataClass: v0.16.0
  Test::More: 0.74
configure_requires:
  Module::Build: 0.38
  version: 0.77
dynamic_config: 1
generated_by: 'Module::Build version 0.4004, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Provision
no_index:
  directory:
    - bin
    - examples
    - inc
    - share
    - t
provides:
  Dist::Zilla::Plugin::ManifestInRoot:
    file: lib/Dist/Zilla/Plugin/ManifestInRoot.pm
    version: v0.7.2
  Module::Provision:
    file: lib/Module/Provision.pm
    version: v0.7.7
recommends:
  App::cpanminus: 1.6005
requires:
  Class::Usul: v0.15.0
  Date::Format: 2.24
  Dist::Zilla: 4.300033
  Dist::Zilla::Plugin::ReadmeAnyFromPod: 0.12012
  Dist::Zilla::Plugin::VersionFromModule: 0.08
  File::DataClass: v0.16.0
  File::ShareDir: 1.02
  File::Slurp: 9999.13
  Module::Build: 0.38
  Module::Install: 1.06
  Module::Install::AutoLicense: 0.08
  Module::Install::ReadmeFromPod: 0.2
  Module::Install::ReadmeMarkdownFromPod: 0.03
  Module::Metadata: 1.000011
  Moose::Autobox: 0.12
  Perl::Version: 1.011
  Pod::Markdown: 1.322
  Template: 2.22
  Text::Format: 0.53
  perl: 5.01
  version: 0.77
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Module-Provision
  homepage: http://www.roxsoft.co.uk
  license: http://dev.perl.org/licenses/
  repository: git://github.com/pjfl/Module-Provision.git
version: v0.7.7
